services:
  # Catalog Service
  - type: web
    name: dacn-catalog
    runtime: node
    repo: https://github.com/HoVietThang190704/BE_DACN_v1.git
    rootDir: apps/catalog
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /products

  # Order Service  
  - type: web
    name: dacn-order
    runtime: node
    repo: https://github.com/HoVietThang190704/BE_DACN_v1.git
    rootDir: apps/order
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /quote-shipping

  # API Gateway
  - type: web
    name: dacn-api-gateway
    runtime: node
    repo: https://github.com/HoVietThang190704/BE_DACN_v1.git
    rootDir: apps/api-gateway
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CATALOG_URL
        value: https://dacn-catalog.onrender.com
      - key: ORDER_URL
        value: https://dacn-order.onrender.com
    healthCheckPath: /health